Question 1 & 3 test passed, question 2 test failed with "TypeError: two() missing 2 required positional arguments: 'bert' and 'bert2'" but prints the results correctly.